In [1]:
import numpy as np
import pandas as pd

In [5]:
students_list = [
    [1, 'Ali', 20, 'Lahore'],
    [2, 'Sara', 21, 'Karachi'],
    [3, 'Ahmed', 19, 'Islamabad'],
    [4, 'Ayesha', 22, 'Lahore'],
    [5, 'Bilal', 20, 'Karachi']
]
cols = ['student_id', 'name', 'age', 'city']
df_std = pd.DataFrame(students_list, columns=cols)

In [6]:
scores = [
    {'student_id': 1, 'subject': 'Maths', 'marks': 85},
    {'student_id': 2, 'subject': 'Maths', 'marks': 90},
    {'student_id': 3, 'subject': 'Maths', 'marks': 75},
    {'student_id': 1, 'subject': 'Physics', 'marks': 80},
    {'student_id': 4, 'subject': 'Physics', 'marks': 88},
    {'student_id': 5, 'subject': 'Maths', 'marks': 70}
]
df_scores = pd.DataFrame(scores)

In [4]:
df_new_entries = pd.DataFrame({
    'student_id': [6, 7],
    'name': ['Hina', 'Usman'],
    'age': [23, 21],
    'city': ['Faisalabad', 'Lahore']
})

In [7]:
print("Students Data:")
display(df_std.head())
print("Scores Data:")
display(df_scores.head())
print("Extra Students:")
display(df_new_entries)

Students Data:

   student_id    name  age       city
0           1     Ali   20     Lahore
1           2    Sara   21    Karachi
2           3   Ahmed   19  Islamabad
3           4  Ayesha   22     Lahore
4           5   Bilal   20    Karachi

Scores Data:

   student_id  subject  marks
0           1    Maths     85
1           2    Maths     90
2           3    Maths     75
3           1  Physics     80
4           4  Physics     88

Extra Students:

   student_id   name  age        city
0           6   Hina   23  Faisalabad
1           7  Usman   21      Lahore

<h3> Merging (Inner, Left, Right) </h3>

In [8]:
merged_inner = df_std.merge(df_scores, on='student_id', how='inner')
merged_left = df_std.merge(df_scores, on='student_id', how='left')
merged_right = df_std.merge(df_scores, on='student_id', how='right')

display(merged_inner.head())
display(merged_left.head())
display(merged_right.head())

   student_id    name  age       city  subject  marks
0           1     Ali   20     Lahore    Maths     85
1           1     Ali   20     Lahore  Physics     80
2           2    Sara   21    Karachi    Maths     90
3           3   Ahmed   19  Islamabad    Maths     75
4           4  Ayesha   22     Lahore  Physics     88

   student_id    name  age       city  subject  marks
0           1     Ali   20     Lahore    Maths     85
1           1     Ali   20     Lahore  Physics     80
2           2    Sara   21    Karachi    Maths     90
3           3   Ahmed   19  Islamabad    Maths     75
4           4  Ayesha   22     Lahore  Physics     88

   student_id    name  age       city  subject  marks
0           1     Ali   20     Lahore    Maths     85
1           2    Sara   21    Karachi    Maths     90
2           3   Ahmed   19  Islamabad    Maths     75
3           1     Ali   20     Lahore  Physics     80
4           4  Ayesha   22     Lahore  Physics     88

<h3>Concatenation</h3>

In [9]:
combined_students = pd.concat([df_std, df_new_entries], axis=0, ignore_index=True)
display(combined_students.tail())

   student_id    name  age        city
2           3   Ahmed   19   Islamabad
3           4  Ayesha   22      Lahore
4           5   Bilal   20     Karachi
5           6    Hina   23  Faisalabad
6           7   Usman   21      Lahore

<h3> Groupby Analysis </h3>

In [10]:
student_avg = merged_inner.groupby('name')[['marks']].agg('mean')
city_avg = merged_inner.groupby('city')[['marks']].mean()

print(f"Mean Marks per Student:\n{student_avg}")
print("-" * 30)
print(f"Mean Marks per City:\n{city_avg}")

Mean Marks per Student:
        marks
name
Ahmed    75.0
Ali      82.5
Ayesha   88.0
Bilal    70.0
Sara     90.0
------------------------------
Mean Marks per City:
               marks
city
Islamabad  75.000000
Karachi    80.000000
Lahore     84.333333

<h3> Bonus (Region Mapping) </h3>

In [11]:
region_map = pd.DataFrame([
    ('Lahore', 'Punjab'),
    ('Karachi', 'Sindh'),
    ('Islamabad', 'Capital'),
    ('Faisalabad', 'Punjab')
], columns=['city', 'region'])

In [12]:
final_dataset = merged_inner.merge(region_map, on='city', how='left')

display(final_dataset.sample(5))

   student_id    name  age       city  subject  marks   region
3           3   Ahmed   19  Islamabad    Maths     75  Capital
2           2    Sara   21    Karachi    Maths     90    Sindh
1           1     Ali   20     Lahore  Physics     80   Punjab
0           1     Ali   20     Lahore    Maths     85   Punjab
4           4  Ayesha   22     Lahore  Physics     88   Punjab