

# **Concantenation AND Joins**

In [3]:
#virtually stack two dataframes
import pandas as pd
Jan=pd.DataFrame({
    'sales': [10,80,90,40],
    'Day' : ['MON','TUE','WED','THUR']
})
Feb=pd.DataFrame({
    'sales': [80,80,40,40],
    'Day' : ['MON','TUE','WED','THUR']
})
print(Jan)
print(Feb)

   sales   Day
0     10   MON
1     80   TUE
2     90   WED
3     40  THUR
   sales   Day
0     80   MON
1     80   TUE
2     40   WED
3     40  THUR

In [4]:
pd.concat([Jan,Feb])

   sales   Day
0     10   MON
1     80   TUE
2     90   WED
3     40  THUR
0     80   MON
1     80   TUE
2     40   WED
3     40  THUR

In [ ]:
#indexes should not repaet
pd.concat([Jan,Feb],ignore_index=True)

   sales   Day
0     10   MON
1     80   TUE
2     90   WED
3     40  THUR
4     80   MON
5     80   TUE
6     40   WED
7     40  THUR

In [ ]:
#Multiindex
multi=pd.concat([Jan,Feb],keys=['Jan','Feb'])
print(multi)

       sales   Day
Jan 0     10   MON
    1     80   TUE
    2     90   WED
    3     40  THUR
Feb 0     80   MON
    1     80   TUE
    2     40   WED
    3     40  THUR

In [ ]:
multi.loc['Jan','Day']

0     MON
1     TUE
2     WED
3    THUR
Name: Day, dtype: object

In [ ]:
#horizontally stack
pd.concat([Jan,Feb],axis=1)

   sales   Day  sales   Day
0     10   MON     80   MON
1     80   TUE     80   TUE
2     90   WED     40   WED
3     40  THUR     40  THUR

# **Joins/Merging**
     Join database on the basis of same column.



### **Joins in pandas**

Joins are used to **combine two DataFrames** based on a **common column(s)** (like SQL joins).

#### **Types of joins**

1. **Inner Join (`how='inner'`)**

   * Returns only rows that have **matching keys in both DataFrames**.
   * Syntax:

     ```python
     pd.merge(df1, df2, on='key', how='inner')
     ```

2. **Left Join (`how='left'`)**

   * Returns **all rows from the left DataFrame**, and matching rows from the right DataFrame.
   * Missing values are filled with `NaN`.
   * Syntax:

     ```python
     pd.merge(df1, df2, on='key', how='left')
     ```

3. **Right Join (`how='right'`)**

   * Returns **all rows from the right DataFrame**, and matching rows from the left DataFrame.
   * Missing values are filled with `NaN`.
   * Syntax:

     ```python
     pd.merge(df1, df2, on='key', how='right')
     ```

4. **Outer Join (`how='outer'`)**

   * Returns **all rows from both DataFrames**, filling `NaN` for missing matches.
   * Syntax:

     ```python
     pd.merge(df1, df2, on='key', how='outer')
     ```

In [ ]:

df1 = pd.DataFrame({
    'student_id': [1, 2, 3, 4, 5],
    'name': ['Ali', 'Sara', 'Hassan', 'Fatima', 'Zain'],
    'city': ['Lahore', 'Karachi', 'Lahore', 'Islamabad', 'Sahiwal']
})

df2 = pd.DataFrame({
    'student_id': [3, 4, 5, 6, 7],
    'marks': [78, 88, 95, 67, 80],
    'result': ['Pass', 'Pass', 'Pass', 'Fail', 'Pass']
})

print(df1)
print(df2)

   student_id    name       city
0           1     Ali     Lahore
1           2    Sara    Karachi
2           3  Hassan     Lahore
3           4  Fatima  Islamabad
4           5    Zain    Sahiwal
   student_id  marks result
0           3     78   Pass
1           4     88   Pass
2           5     95   Pass
3           6     67   Fail
4           7     80   Pass

In [ ]:
#inner join
pd.merge(df1,df2,on='student_id',how='inner')

   student_id    name       city  marks result
0           3  Hassan     Lahore     78   Pass
1           4  Fatima  Islamabad     88   Pass
2           5    Zain    Sahiwal     95   Pass

In [ ]:
#left join
pd.merge(df1,df2,on='student_id',how='left')

   student_id    name       city  marks result
0           1     Ali     Lahore    NaN    NaN
1           2    Sara    Karachi    NaN    NaN
2           3  Hassan     Lahore   78.0   Pass
3           4  Fatima  Islamabad   88.0   Pass
4           5    Zain    Sahiwal   95.0   Pass

In [ ]:
#right join
pd.merge(df1,df2,on='student_id',how='right')

   student_id    name       city  marks result
0           3  Hassan     Lahore     78   Pass
1           4  Fatima  Islamabad     88   Pass
2           5    Zain    Sahiwal     95   Pass
3           6     NaN        NaN     67   Fail
4           7     NaN        NaN     80   Pass

In [ ]:
#full
pd.merge(df1,df2,on='student_id',how='outer')

   student_id    name       city  marks result
0           1     Ali     Lahore    NaN    NaN
1           2    Sara    Karachi    NaN    NaN
2           3  Hassan     Lahore   78.0   Pass
3           4  Fatima  Islamabad   88.0   Pass
4           5    Zain    Sahiwal   95.0   Pass
5           6     NaN        NaN   67.0   Fail
6           7     NaN        NaN   80.0   Pass

# **Filteration**

In [ ]:
# 1. Find all students who scored more tahn 80.

In [ ]:
a1=pd.merge(df1,df2,on='student_id',how="inner")
a1[a1['marks'] > 80]

   student_id    name       city  marks result
1           4  Fatima  Islamabad     88   Pass
2           5    Zain    Sahiwal     95   Pass

In [ ]:

# 2. find the students who have'nt taken test.
a2=pd.merge(df1,df2,on='student_id',how="left")
a2[a2['marks'].isna()]

   student_id  name     city  marks result
0           1   Ali   Lahore    NaN    NaN
1           2  Sara  Karachi    NaN    NaN

In [ ]:
# 3. Find students who have both personal info and marks recorded and passed the exam (result == "Pass") and scored more than 90.
a1[(a1['marks'] > 90) & (a1['result'] == 'Pass')]

   student_id  name     city  marks result
2           5  Zain  Sahiwal     95   Pass

In [ ]:
#4 .  Find students whose names contain the letter "a" and have marks recorded.
a1[a1['name'].str.contains('a')]

   student_id    name       city  marks result
0           3  Hassan     Lahore     78   Pass
1           4  Fatima  Islamabad     88   Pass
2           5    Zain    Sahiwal     95   Pass