# **Data Analysis Process**

Inspecting, cleaning, transforming, and modeling data with the goal of discovering useful information.

# **5 Steps Process**


1.   Asking QS  ( what faetures are imp for my data, is it need preprocessing)
2.   Data Wrangling/Munging
3.   EDA
4.   Drawing Conclusions
5.   Communicate Resulst

# **Data Wrangling/Munging**
1.  Gathering Data
2.  Acess data (shape,columns,rows)
3.  Cleaning Data

# **Data Gathering**

In [ ]:
#1. opening a local csv file
import pandas as pd
pd.read_csv('students2.csv')

             name  marks result gender
0     Ayesha Khan     78   Pass      F
1        Ali Raza     55   Pass      M
2    Hassan Ahmed     32   Fail      M
3     Fatima Noor     89   Pass      F
4      Zain Malik     64   Pass      M
5      Sara Zafar     92   Pass      F
6     Umer Farooq     27   Fail      M
7     Maryam Shah     81   Pass      F
8     Hamza Tariq     40   Pass      M
9     Laiba Irfan     36   Fail      F
10  Bilal Hussain     73   Pass      M
11     Iqra Javed     59   Pass      F
12    Ahmad Kamal     44   Pass      M
13     Hina Aslam     25   Fail      F
14   Usman Khalid     88   Pass      M
15   Nimra Yousaf     67   Pass      F
16   Danish Iqbal     30   Fail      M
17   Sadia Rehman     91   Pass      F
18  Taha Siddiqui     48   Pass      M
19    Mehwish Ali     34   Fail      F
20  Shahzaib Khan     62   Pass      M
21   Areeba Waqar     95   Pass      F
22    Junaid Arif     29   Fail      M
23    Sana Fatima     82   Pass      F
24  Talha Murtaza     53   Pass      M
25  Mariam Rehman     37   Fail      F
26   Shehryar Ali     69   Pass      M
27   Eman Qureshi     58   Pass      F
28   Ammar Siddiq     31   Fail      M
29  Hoorain Abbas     87   Pass      F

In [ ]:
# 2. Sep Parameter
pd.read_csv('students2.csv',sep=' ')

         name,marks,result,gender
Ayesha             Khan,78,Pass,F
Ali                Raza,55,Pass,M
Hassan            Ahmed,32,Fail,M
Fatima             Noor,89,Pass,F
Zain              Malik,64,Pass,M
Sara              Zafar,92,Pass,F
Umer             Farooq,27,Fail,M
Maryam             Shah,81,Pass,F
Hamza             Tariq,40,Pass,M
Laiba             Irfan,36,Fail,F
Bilal           Hussain,73,Pass,M
Iqra              Javed,59,Pass,F
Ahmad             Kamal,44,Pass,M
Hina              Aslam,25,Fail,F
Usman            Khalid,88,Pass,M
Nimra            Yousaf,67,Pass,F
Danish            Iqbal,30,Fail,M
Sadia            Rehman,91,Pass,F
Taha           Siddiqui,48,Pass,M
Mehwish             Ali,34,Fail,F
Shahzaib           Khan,62,Pass,M
Areeba            Waqar,95,Pass,F
Junaid             Arif,29,Fail,M
Sana             Fatima,82,Pass,F
Talha           Murtaza,53,Pass,M
Mariam           Rehman,37,Fail,F
Shehryar            Ali,69,Pass,M
Eman            Qureshi,58,Pass,F
Ammar            Siddiq,31,Fail,M
Hoorain           Abbas,87,Pass,F

In [ ]:
#3. Index_col Parameter (customize index)
pd.read_csv('students2.csv',index_col='name')

               marks result gender
name
Ayesha Khan       78   Pass      F
Ali Raza          55   Pass      M
Hassan Ahmed      32   Fail      M
Fatima Noor       89   Pass      F
Zain Malik        64   Pass      M
Sara Zafar        92   Pass      F
Umer Farooq       27   Fail      M
Maryam Shah       81   Pass      F
Hamza Tariq       40   Pass      M
Laiba Irfan       36   Fail      F
Bilal Hussain     73   Pass      M
Iqra Javed        59   Pass      F
Ahmad Kamal       44   Pass      M
Hina Aslam        25   Fail      F
Usman Khalid      88   Pass      M
Nimra Yousaf      67   Pass      F
Danish Iqbal      30   Fail      M
Sadia Rehman      91   Pass      F
Taha Siddiqui     48   Pass      M
Mehwish Ali       34   Fail      F
Shahzaib Khan     62   Pass      M
Areeba Waqar      95   Pass      F
Junaid Arif       29   Fail      M
Sana Fatima       82   Pass      F
Talha Murtaza     53   Pass      M
Mariam Rehman     37   Fail      F
Shehryar Ali      69   Pass      M
Eman Qureshi      58   Pass      F
Ammar Siddiq      31   Fail      M
Hoorain Abbas     87   Pass      F

In [ ]:
#4. use_cols parameter (specify the column during import time)
pd.read_csv('students2.csv', usecols=['marks'])

    marks
0      78
1      55
2      32
3      89
4      64
5      92
6      27
7      81
8      40
9      36
10     73
11     59
12     44
13     25
14     88
15     67
16     30
17     91
18     48
19     34
20     62
21     95
22     29
23     82
24     53
25     37
26     69
27     58
28     31
29     87

In [ ]:
#mutiple columns
pd.read_csv('students2.csv', usecols=['name', 'marks'])

             name  marks
0     Ayesha Khan     78
1        Ali Raza     55
2    Hassan Ahmed     32
3     Fatima Noor     89
4      Zain Malik     64
5      Sara Zafar     92
6     Umer Farooq     27
7     Maryam Shah     81
8     Hamza Tariq     40
9     Laiba Irfan     36
10  Bilal Hussain     73
11     Iqra Javed     59
12    Ahmad Kamal     44
13     Hina Aslam     25
14   Usman Khalid     88
15   Nimra Yousaf     67
16   Danish Iqbal     30
17   Sadia Rehman     91
18  Taha Siddiqui     48
19    Mehwish Ali     34
20  Shahzaib Khan     62
21   Areeba Waqar     95
22    Junaid Arif     29
23    Sana Fatima     82
24  Talha Murtaza     53
25  Mariam Rehman     37
26   Shehryar Ali     69
27   Eman Qureshi     58
28   Ammar Siddiq     31
29  Hoorain Abbas     87

In [ ]:
#skip the first n rows
pd.read_csv("students2.csv", skiprows=5)

       Zain Malik  64  Pass  M
0      Sara Zafar  92  Pass  F
1     Umer Farooq  27  Fail  M
2     Maryam Shah  81  Pass  F
3     Hamza Tariq  40  Pass  M
4     Laiba Irfan  36  Fail  F
5   Bilal Hussain  73  Pass  M
6      Iqra Javed  59  Pass  F
7     Ahmad Kamal  44  Pass  M
8      Hina Aslam  25  Fail  F
9    Usman Khalid  88  Pass  M
10   Nimra Yousaf  67  Pass  F
11   Danish Iqbal  30  Fail  M
12   Sadia Rehman  91  Pass  F
13  Taha Siddiqui  48  Pass  M
14    Mehwish Ali  34  Fail  F
15  Shahzaib Khan  62  Pass  M
16   Areeba Waqar  95  Pass  F
17    Junaid Arif  29  Fail  M
18    Sana Fatima  82  Pass  F
19  Talha Murtaza  53  Pass  M
20  Mariam Rehman  37  Fail  F
21   Shehryar Ali  69  Pass  M
22   Eman Qureshi  58  Pass  F
23   Ammar Siddiq  31  Fail  M
24  Hoorain Abbas  87  Pass  F

In [ ]:
#skip specific rows
pd.read_csv("students2.csv", skiprows=[1, 2, 5])

             name  marks result gender
0    Hassan Ahmed     32   Fail      M
1     Fatima Noor     89   Pass      F
2      Sara Zafar     92   Pass      F
3     Umer Farooq     27   Fail      M
4     Maryam Shah     81   Pass      F
5     Hamza Tariq     40   Pass      M
6     Laiba Irfan     36   Fail      F
7   Bilal Hussain     73   Pass      M
8      Iqra Javed     59   Pass      F
9     Ahmad Kamal     44   Pass      M
10     Hina Aslam     25   Fail      F
11   Usman Khalid     88   Pass      M
12   Nimra Yousaf     67   Pass      F
13   Danish Iqbal     30   Fail      M
14   Sadia Rehman     91   Pass      F
15  Taha Siddiqui     48   Pass      M
16    Mehwish Ali     34   Fail      F
17  Shahzaib Khan     62   Pass      M
18   Areeba Waqar     95   Pass      F
19    Junaid Arif     29   Fail      M
20    Sana Fatima     82   Pass      F
21  Talha Murtaza     53   Pass      M
22  Mariam Rehman     37   Fail      F
23   Shehryar Ali     69   Pass      M
24   Eman Qureshi     58   Pass      F
25   Ammar Siddiq     31   Fail      M
26  Hoorain Abbas     87   Pass      F

In [ ]:
#read only first n rows
pd.read_csv("students2.csv", nrows=10)

           name  marks result gender
0   Ayesha Khan     78   Pass      F
1      Ali Raza     55   Pass      M
2  Hassan Ahmed     32   Fail      M
3   Fatima Noor     89   Pass      F
4    Zain Malik     64   Pass      M
5    Sara Zafar     92   Pass      F
6   Umer Farooq     27   Fail      M
7   Maryam Shah     81   Pass      F
8   Hamza Tariq     40   Pass      M
9   Laiba Irfan     36   Fail      F

In [ ]:
#na vlaue parameter
pd.read_csv("students2.csv", na_values=['-','no','M'])

             name  marks result gender
0     Ayesha Khan     78   Pass      F
1        Ali Raza     55   Pass    NaN
2    Hassan Ahmed     32   Fail    NaN
3     Fatima Noor     89   Pass      F
4      Zain Malik     64   Pass    NaN
5      Sara Zafar     92   Pass      F
6     Umer Farooq     27   Fail    NaN
7     Maryam Shah     81   Pass      F
8     Hamza Tariq     40   Pass    NaN
9     Laiba Irfan     36   Fail      F
10  Bilal Hussain     73   Pass    NaN
11     Iqra Javed     59   Pass      F
12    Ahmad Kamal     44   Pass    NaN
13     Hina Aslam     25   Fail      F
14   Usman Khalid     88   Pass    NaN
15   Nimra Yousaf     67   Pass      F
16   Danish Iqbal     30   Fail    NaN
17   Sadia Rehman     91   Pass      F
18  Taha Siddiqui     48   Pass    NaN
19    Mehwish Ali     34   Fail      F
20  Shahzaib Khan     62   Pass    NaN
21   Areeba Waqar     95   Pass      F
22    Junaid Arif     29   Fail    NaN
23    Sana Fatima     82   Pass      F
24  Talha Murtaza     53   Pass    NaN
25  Mariam Rehman     37   Fail      F
26   Shehryar Ali     69   Pass    NaN
27   Eman Qureshi     58   Pass      F
28   Ammar Siddiq     31   Fail    NaN
29  Hoorain Abbas     87   Pass      F

In [ ]:
#read excel file
pd.read_excel('students2.xlsx')

    Unnamed: 0           name  marks result gender
0            0    Ayesha Khan     78   Pass      F
1            1       Ali Raza     55   Pass      M
2            2   Hassan Ahmed     32   Fail      M
3            3    Fatima Noor     89   Pass      F
4            4     Zain Malik     64   Pass      M
5            5     Sara Zafar     92   Pass      F
6            6    Umer Farooq     27   Fail      M
7            7    Maryam Shah     81   Pass      F
8            8    Hamza Tariq     40   Pass      M
9            9    Laiba Irfan     36   Fail      F
10          10  Bilal Hussain     73   Pass      M
11          11     Iqra Javed     59   Pass      F
12          12    Ahmad Kamal     44   Pass      M
13          13     Hina Aslam     25   Fail      F
14          14   Usman Khalid     88   Pass      M
15          15   Nimra Yousaf     67   Pass      F
16          16   Danish Iqbal     30   Fail      M
17          17   Sadia Rehman     91   Pass      F
18          18  Taha Siddiqui     48   Pass      M
19          19    Mehwish Ali     34   Fail      F
20          20  Shahzaib Khan     62   Pass      M
21          21   Areeba Waqar     95   Pass      F
22          22    Junaid Arif     29   Fail      M
23          23    Sana Fatima     82   Pass      F
24          24  Talha Murtaza     53   Pass      M
25          25  Mariam Rehman     37   Fail      F
26          26   Shehryar Ali     69   Pass      M
27          27   Eman Qureshi     58   Pass      F
28          28   Ammar Siddiq     31   Fail      M
29          29  Hoorain Abbas     87   Pass      F

In [ ]:
#sheet_name='sheet1'

In [ ]:
#txt file
#pd.read_csv(_,sep='\t')

In [ ]:
#json file (raed json but retuen dataframe)
pd.read_json('students2.json')

             name  marks result gender
0     Ayesha Khan     78   Pass      F
1        Ali Raza     55   Pass      M
2    Hassan Ahmed     32   Fail      M
3     Fatima Noor     89   Pass      F
4      Zain Malik     64   Pass      M
5      Sara Zafar     92   Pass      F
6     Umer Farooq     27   Fail      M
7     Maryam Shah     81   Pass      F
8     Hamza Tariq     40   Pass      M
9     Laiba Irfan     36   Fail      F
10  Bilal Hussain     73   Pass      M
11     Iqra Javed     59   Pass      F
12    Ahmad Kamal     44   Pass      M
13     Hina Aslam     25   Fail      F
14   Usman Khalid     88   Pass      M
15   Nimra Yousaf     67   Pass      F
16   Danish Iqbal     30   Fail      M
17   Sadia Rehman     91   Pass      F
18  Taha Siddiqui     48   Pass      M
19    Mehwish Ali     34   Fail      F
20  Shahzaib Khan     62   Pass      M
21   Areeba Waqar     95   Pass      F
22    Junaid Arif     29   Fail      M
23    Sana Fatima     82   Pass      F
24  Talha Murtaza     53   Pass      M
25  Mariam Rehman     37   Fail      F
26   Shehryar Ali     69   Pass      M
27   Eman Qureshi     58   Pass      F
28   Ammar Siddiq     31   Fail      M
29  Hoorain Abbas     87   Pass      F

# **Export**

In [ ]:
#excel
a=pd.read_csv('students2.csv')
a.to_excel('students2.xlsx')

In [ ]:
#json
a.to_json('students2.json')

In [ ]:
#html
a.to_html('students2.html')

# **Class Activity**


**1. Import CSV File**

* Import the file `sales.csv` into a pandas DataFrame.
* Display the first few rows of the DataFrame.

**2. Access Data Information**

* Find the shape of the DataFrame.
* Find the number of dimensions.
* Find the number of rows and columns.

**3. Concatenate with Another File**

* Import the second CSV file `sales_additional.csv`.
* Concatenate it with the first DataFrame.
* Display the first few rows and the new shape of the concatenated DataFrame.

**4. Select Important Columns**

* From the concatenated DataFrame, select the two most important columns
* Store them in a new DataFrame.
* Display the first few rows of this new DataFrame.

**5. Export to JSON**

* Export the new DataFrame with selected columns into a JSON file named `sales_selected.json`.