# **Pandas**

# **Group By**

1.   Makes Groups on teh basis of some columns.
2.   Categorical Columns are used for this.

In [13]:
import pandas as pd
a=pd.read_csv('students2.csv')
a

             name  marks result gender
0     Ayesha Khan     78   Pass      F
1        Ali Raza     55   Pass      M
2    Hassan Ahmed     32   Fail      M
3     Fatima Noor     89   Pass      F
4      Zain Malik     64   Pass      M
5      Sara Zafar     92   Pass      F
6     Umer Farooq     27   Fail      M
7     Maryam Shah     81   Pass      F
8     Hamza Tariq     40   Pass      M
9     Laiba Irfan     36   Fail      F
10  Bilal Hussain     73   Pass      M
11     Iqra Javed     59   Pass      F
12    Ahmad Kamal     44   Pass      M
13     Hina Aslam     25   Fail      F
14   Usman Khalid     88   Pass      M
15   Nimra Yousaf     67   Pass      F
16   Danish Iqbal     30   Fail      M
17   Sadia Rehman     91   Pass      F
18  Taha Siddiqui     48   Pass      M
19    Mehwish Ali     34   Fail      F
20  Shahzaib Khan     62   Pass      M
21   Areeba Waqar     95   Pass      F
22    Junaid Arif     29   Fail      M
23    Sana Fatima     82   Pass      F
24  Talha Murtaza     53   Pass      M
25  Mariam Rehman     37   Fail      F
26   Shehryar Ali     69   Pass      M
27   Eman Qureshi     58   Pass      F
28   Ammar Siddiq     31   Fail      M
29  Hoorain Abbas     87   Pass      F

In [14]:
a['city']='Lahore'
a

             name  marks result gender    city
0     Ayesha Khan     78   Pass      F  Lahore
1        Ali Raza     55   Pass      M  Lahore
2    Hassan Ahmed     32   Fail      M  Lahore
3     Fatima Noor     89   Pass      F  Lahore
4      Zain Malik     64   Pass      M  Lahore
5      Sara Zafar     92   Pass      F  Lahore
6     Umer Farooq     27   Fail      M  Lahore
7     Maryam Shah     81   Pass      F  Lahore
8     Hamza Tariq     40   Pass      M  Lahore
9     Laiba Irfan     36   Fail      F  Lahore
10  Bilal Hussain     73   Pass      M  Lahore
11     Iqra Javed     59   Pass      F  Lahore
12    Ahmad Kamal     44   Pass      M  Lahore
13     Hina Aslam     25   Fail      F  Lahore
14   Usman Khalid     88   Pass      M  Lahore
15   Nimra Yousaf     67   Pass      F  Lahore
16   Danish Iqbal     30   Fail      M  Lahore
17   Sadia Rehman     91   Pass      F  Lahore
18  Taha Siddiqui     48   Pass      M  Lahore
19    Mehwish Ali     34   Fail      F  Lahore
20  Shahzaib Khan     62   Pass      M  Lahore
21   Areeba Waqar     95   Pass      F  Lahore
22    Junaid Arif     29   Fail      M  Lahore
23    Sana Fatima     82   Pass      F  Lahore
24  Talha Murtaza     53   Pass      M  Lahore
25  Mariam Rehman     37   Fail      F  Lahore
26   Shehryar Ali     69   Pass      M  Lahore
27   Eman Qureshi     58   Pass      F  Lahore
28   Ammar Siddiq     31   Fail      M  Lahore
29  Hoorain Abbas     87   Pass      F  Lahore

In [15]:
print(type(a))

<class 'pandas.core.frame.DataFrame'>

In [16]:
a.loc[5:10,'city']='Karachi'
a.loc[11:15,'city']='Islamabad'
a.loc[16:29,'city']='Sahiwal'

In [17]:
print(a)

             name  marks result gender       city
0     Ayesha Khan     78   Pass      F     Lahore
1        Ali Raza     55   Pass      M     Lahore
2    Hassan Ahmed     32   Fail      M     Lahore
3     Fatima Noor     89   Pass      F     Lahore
4      Zain Malik     64   Pass      M     Lahore
5      Sara Zafar     92   Pass      F    Karachi
6     Umer Farooq     27   Fail      M    Karachi
7     Maryam Shah     81   Pass      F    Karachi
8     Hamza Tariq     40   Pass      M    Karachi
9     Laiba Irfan     36   Fail      F    Karachi
10  Bilal Hussain     73   Pass      M    Karachi
11     Iqra Javed     59   Pass      F  Islamabad
12    Ahmad Kamal     44   Pass      M  Islamabad
13     Hina Aslam     25   Fail      F  Islamabad
14   Usman Khalid     88   Pass      M  Islamabad
15   Nimra Yousaf     67   Pass      F  Islamabad
16   Danish Iqbal     30   Fail      M    Sahiwal
17   Sadia Rehman     91   Pass      F    Sahiwal
18  Taha Siddiqui     48   Pass      M    Sahiwal
19    Mehwish Ali     34   Fail      F    Sahiwal
20  Shahzaib Khan     62   Pass      M    Sahiwal
21   Areeba Waqar     95   Pass      F    Sahiwal
22    Junaid Arif     29   Fail      M    Sahiwal
23    Sana Fatima     82   Pass      F    Sahiwal
24  Talha Murtaza     53   Pass      M    Sahiwal
25  Mariam Rehman     37   Fail      F    Sahiwal
26   Shehryar Ali     69   Pass      M    Sahiwal
27   Eman Qureshi     58   Pass      F    Sahiwal
28   Ammar Siddiq     31   Fail      M    Sahiwal
29  Hoorain Abbas     87   Pass      F    Sahiwal

In [19]:
a.loc[a.sample(1).index, 'city'] = 'narowal'
a

             name  marks result gender       city
0     Ayesha Khan     78   Pass      F     Lahore
1        Ali Raza     55   Pass      M     Lahore
2    Hassan Ahmed     32   Fail      M     Lahore
3     Fatima Noor     89   Pass      F    narowal
4      Zain Malik     64   Pass      M     Lahore
5      Sara Zafar     92   Pass      F    Karachi
6     Umer Farooq     27   Fail      M    Karachi
7     Maryam Shah     81   Pass      F    Karachi
8     Hamza Tariq     40   Pass      M    Karachi
9     Laiba Irfan     36   Fail      F    Karachi
10  Bilal Hussain     73   Pass      M    Karachi
11     Iqra Javed     59   Pass      F  Islamabad
12    Ahmad Kamal     44   Pass      M  Islamabad
13     Hina Aslam     25   Fail      F  Islamabad
14   Usman Khalid     88   Pass      M  Islamabad
15   Nimra Yousaf     67   Pass      F  Islamabad
16   Danish Iqbal     30   Fail      M    Sahiwal
17   Sadia Rehman     91   Pass      F    Sahiwal
18  Taha Siddiqui     48   Pass      M    Sahiwal
19    Mehwish Ali     34   Fail      F    Sahiwal
20  Shahzaib Khan     62   Pass      M    Sahiwal
21   Areeba Waqar     95   Pass      F    Sahiwal
22    Junaid Arif     29   Fail      M    Sahiwal
23    Sana Fatima     82   Pass      F    Sahiwal
24  Talha Murtaza     53   Pass      M    Sahiwal
25  Mariam Rehman     37   Fail      F    Sahiwal
26   Shehryar Ali     69   Pass      M    Sahiwal
27   Eman Qureshi     58   Pass      F    Sahiwal
28   Ammar Siddiq     31   Fail      M    Sahiwal
29  Hoorain Abbas     87   Pass      F    Sahiwal

In [21]:
#now amke groups based on city column
group=a.groupby('city')
group

In [22]:
#gives you all groups names in dictionary (sorted)
group.groups

{'Islamabad': [11, 12, 13, 14, 15], 'Karachi': [5, 6, 7, 8, 9, 10], 'Lahore': [0, 1, 2, 4], 'Sahiwal': [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], 'narowal': [3]}

In [23]:
#get_group (give you information about specific group)
group.get_group('Lahore')

           name  marks result gender    city
0   Ayesha Khan     78   Pass      F  Lahore
1      Ali Raza     55   Pass      M  Lahore
2  Hassan Ahmed     32   Fail      M  Lahore
4    Zain Malik     64   Pass      M  Lahore

In [25]:
#describe (give information for all groups)
group.describe()

          marks
          count       mean        std   min    25%   50%    75%   max
city
Islamabad   5.0  56.600000  23.754999  25.0  44.00  59.0  67.00  88.0
Karachi     6.0  58.166667  27.125019  27.0  37.00  56.5  79.00  92.0
Lahore      4.0  57.250000  19.311050  32.0  49.25  59.5  67.50  78.0
Sahiwal    14.0  57.571429  24.027914  29.0  34.75  55.5  78.75  95.0
narowal     1.0  89.000000        NaN  89.0  89.00  89.0  89.00  89.0

In [26]:
#randomly fetch any row from all groups
group.sample()

            name  marks result gender       city
13    Hina Aslam     25   Fail      F  Islamabad
8    Hamza Tariq     40   Pass      M    Karachi
2   Hassan Ahmed     32   Fail      M     Lahore
21  Areeba Waqar     95   Pass      F    Sahiwal
3    Fatima Noor     89   Pass      F    narowal

In [27]:
#find total len of groups
len(group)

5

In [28]:
#find items in each group
group.size()

city
Islamabad     5
Karachi       6
Lahore        4
Sahiwal      14
narowal       1
dtype: int64

In [29]:
#first item in each group
group.first()

                   name  marks result gender
city
Islamabad    Iqra Javed     59   Pass      F
Karachi      Sara Zafar     92   Pass      F
Lahore      Ayesha Khan     78   Pass      F
Sahiwal    Danish Iqbal     30   Fail      M
narowal     Fatima Noor     89   Pass      F

In [30]:
#last item in each group
group.last()

                    name  marks result gender
city
Islamabad   Nimra Yousaf     67   Pass      F
Karachi    Bilal Hussain     73   Pass      M
Lahore        Zain Malik     64   Pass      M
Sahiwal    Hoorain Abbas     87   Pass      F
narowal      Fatima Noor     89   Pass      F

In [31]:
#nth item in each group
group.nth(2)

             name  marks result gender       city
2    Hassan Ahmed     32   Fail      M     Lahore
7     Maryam Shah     81   Pass      F    Karachi
13     Hina Aslam     25   Fail      F  Islamabad
18  Taha Siddiqui     48   Pass      M    Sahiwal

# **Aggregate Functions on Group**

In [32]:
group.sum()

,name,marks,result,gender
city,,,,
Islamabad,Iqra JavedAhmad KamalHina AslamUsman KhalidNim...,283,PassPassFailPassPass,FMFMF
Karachi,Sara ZafarUmer FarooqMaryam ShahHamza TariqLai...,349,PassFailPassPassFailPass,FMFMFM
Lahore,Ayesha KhanAli RazaHassan AhmedZain Malik,229,PassPassFailPass,FMMM
Sahiwal,Danish IqbalSadia RehmanTaha SiddiquiMehwish A...,806,FailPassPassFailPassPassFailPassPassFailPassPa...,MFMFMFMFMFMFMF
narowal,Fatima Noor,89,Pass,F

In [36]:
group.min()

                    name  marks result gender
city
Islamabad    Ahmad Kamal     25   Fail      F
Karachi    Bilal Hussain     27   Fail      F
Lahore          Ali Raza     32   Fail      F
Sahiwal     Ammar Siddiq     29   Fail      F
narowal      Fatima Noor     89   Pass      F

In [37]:
group.mean(numeric_only=True)

               marks
city
Islamabad  56.600000
Karachi    58.166667
Lahore     57.250000
Sahiwal    57.571429
narowal    89.000000

In [38]:
group['marks'].max()

city
Islamabad    88
Karachi      92
Lahore       78
Sahiwal      95
narowal      89
Name: marks, dtype: int64

# **Filteration (Practise Qs)**

In [39]:
#1 Average marks per city

group['marks'].mean()

city
Islamabad    56.600000
Karachi      58.166667
Lahore       57.250000
Sahiwal      57.571429
narowal      89.000000
Name: marks, dtype: float64

In [46]:
#Count of students per result

# Group by result and find how many students passed and failed.
group_by_result=a.groupby('result')
group_by_result.size()

result
Fail     9
Pass    21
dtype: int64

In [ ]:
# Highest marks in each city

# Group by city and find the maximum marks in each city.

In [48]:
group['marks'].max()

city
Islamabad    88
Karachi      92
Lahore       78
Sahiwal      95
narowal      89
Name: marks, dtype: int64

In [ ]:
# Female students’ average marks per city

# Group by city but only include female students (gender=='F).

# Calculate average marks for each city.

In [51]:
f_stu=a.loc[a['gender']=='F',:]
g_f_stu=f_stu.groupby('city')
g_f_stu['marks'].mean()

city
Islamabad    50.333333
Karachi      69.666667
Lahore       78.000000
Sahiwal      69.142857
narowal      89.000000
Name: marks, dtype: float64

In [52]:
a[a['gender']=='F'].groupby('city')['marks'].mean()

city
Islamabad    50.333333
Karachi      69.666667
Lahore       78.000000
Sahiwal      69.142857
narowal      89.000000
Name: marks, dtype: float64

In [60]:
#  Students scoring more than 70 in each city

# Group by city.

# For each city, list students with marks > 70.
a[a['marks'] > 70].groupby('city')['name'].apply(list)

city
Islamabad                                       [Usman Khalid]
Karachi               [Sara Zafar, Maryam Shah, Bilal Hussain]
Lahore                                           [Ayesha Khan]
Sahiwal      [Sadia Rehman, Areeba Waqar, Sana Fatima, Hoor...
narowal                                          [Fatima Noor]
Name: name, dtype: object

In [65]:
#  Count of students who failed per city
a[a['result'] == 'Fail'].groupby('city')['name'].count()

city
Islamabad    1
Karachi      2
Lahore       1
Sahiwal      5
Name: name, dtype: int64

In [66]:
# Minimum and maximum marks per city
#agg() apply more aggregate function on same column at 1 time
group['marks'].agg(['min','max'])

           min  max
city
Islamabad   25   88
Karachi     27   92
Lahore      32   78
Sahiwal     29   95
narowal     89   89

In [68]:
#  Average marks of male and female students separately
group_by_gendr=a.groupby('gender')['marks'].mean()
group_by_gendr

gender
F    67.400000
M    49.666667
Name: marks, dtype: float64

In [70]:
#  Cities where average marks > 60
avg_marks = group['marks'].mean()
avg_marks[avg_marks > 60]

city
narowal    89.0
Name: marks, dtype: float64

In [74]:
# Top scorer per city
# idxmax returning the index of row with max marks
a.loc[group['marks'].idxmax(), ['city','name','marks']]

         city          name  marks
14  Islamabad  Usman Khalid     88
5     Karachi    Sara Zafar     92
0      Lahore   Ayesha Khan     78
21    Sahiwal  Areeba Waqar     95
3     narowal   Fatima Noor     89

**How Groupby works internally?**


# 🔹 Split-Apply-Combine Strategy

The **Split-Apply-Combine** paradigm describes **how pandas `groupby` works internally**.

---

## 1️⃣ **Split**

* The data is **split into groups** based on a key.
* Usually, you use `groupby()` for this.

Example: split students by `city`:

```python
group = a.groupby('city')
```

* `group` now has **5 groups**: Lahore, Karachi, Islamabad, Sahiwal, Narowal
* Each group contains all rows for that city.

---

## 2️⃣ **Apply**

* Apply a **function** to each group separately.
* Functions can be: sum, mean, max, custom lambda functions, etc.

Example: calculate **average marks per city**:

```python
group['marks'].mean()
```

* pandas calculates the **mean of marks** in each city group individually.

---

## 3️⃣ **Combine**

* The results from each group are **combined back into a single DataFrame or Series**.

Example:

```
city
Karachi      57.4
Lahore       56.3
Islamabad    56.6
Sahiwal      56.7
narowal      89.0
Name: marks, dtype: float64
```

* You now have a **summary Series/DataFrame** with one row per group.



---

In [75]:
#group by on multiple columns
group_by_2=a.groupby(['city','gender'])
group_by_2.groups

{('Islamabad', 'F'): [11, 13, 15], ('Islamabad', 'M'): [12, 14], ('Karachi', 'F'): [5, 7, 9], ('Karachi', 'M'): [6, 8, 10], ('Lahore', 'F'): [0], ('Lahore', 'M'): [1, 2, 4], ('Sahiwal', 'F'): [17, 19, 21, 23, 25, 27, 29], ('Sahiwal', 'M'): [16, 18, 20, 22, 24, 26, 28], ('narowal', 'F'): [3]}